name: Build Executables
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build executable - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
        graalvm-version: ['22.0.0.2']
        java-version: ['17']
        include:
          - os: ubuntu-20.04
            executable-suffix: ''
          - os: macos-latest
            executable-suffix: ''
          - os: windows-2019
            executable-suffix: '.exe'

    steps:
      - name: Setup swap space
        if: runner.os == 'Linux'
        uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c
        with:
          swap-size-gb: 10

      - name: Configure pagefile
        uses: al-cheb/configure-pagefile-action@7e234852c937eea04d6ee627c599fb24a5bfffee
        if: runner.os == 'Windows'
        with:
          minimum-size: 10GB
          maximum-size: 12GB

      - name: Setup pagefile
        if: runner.os == 'Windows'
        run: |
          (Get-CimInstance Win32_PageFileUsage).AllocatedBaseSize
        shell: pwsh

      - uses: actions/checkout@v3
      - id: executable
        run: echo "::set-output name=name::hyperid-${{ runner.os }}-${{ github.event.release.tag_name || 'snapshot' }}-x86_64"

      - name: Setup GraalVM (Java ${{ matrix.java-version }})
        uses: graalvm/setup-graalvm@v1
        with:
          version: '${{ matrix.graalvm-version }}'
          java-version: '${{ matrix.java-version }}'
          components: 'native-image'

      - name: Build ${{ steps.executable.outputs.name }} native image
        run: gradle nativeCompile

      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.executable.outputs.name }}
          path: build/native/nativeCompile/hyper-id-backend${{ matrix.executable-suffix }}
